### ISSUE TITLE
Data is not refreshed on page load

### ISSUE THREAD

**Issue by ColinMaudry** [MTES-MCT/trackdechets-public-stats#8]
## Current behaviour

When the user loads the page, no query is ran against the database. If caching is enabled, it's not hit.

## Expected behaviour

Loading the page triggers the queries or the cache.

## Solution

The problem is similar to the one described [here](https://stackoverflow.com/questions/63502062/python-dash-refresh-page-not-updating-source-data).

The `add_callout` function must not include the figure object, it should be injected into the layout by a callback.

This callback would be variables such as `bsdd_created_weekly` turned into callbacks, or added as outputs to the `get_bsdd_created()` function turned into a callback.

In the meantime, the app must be restarted every Monday morning. On the good side, the app loads fast 🚀

**Comment by Lawiss** [comment]
Issue has been solved with v1.5 of the app.
